name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev gcc-aarch64-linux-gnu

    - name: Install target for aarch64
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Build
      run: cargo build --release --target=aarch64-unknown-linux-gnu

    - name: Create zip file of the build artifacts
      run: |
        mkdir -p artifacts
        cp target/aarch64-unknown-linux-gnu/release/main artifacts/
        cp target/aarch64-unknown-linux-gnu/release/light_control artifacts/
        cp target/aarch64-unknown-linux-gnu/release/sensor_control artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: artifacts/